services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromService:
          name: mariadb
          type: pserv
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: laravel_db
      - key: DB_USERNAME
        value: laravel_user
      - key: DB_PASSWORD
        value: motdepasse

databases:
  - name: mariadb
    databaseName: laravel_db
    user: laravel_user
